((nil (create-lockfiles . nil)
      (projectile-project-compilation-cmd . "make build")
      (projectile-project-run-cmd . "make build run")
      (projectile-project-test-cmd . "make test")
      (projectile-project-configure-cmd . "make refresh-extension")))
